# Numpy practice

After going through the [Intro_to_numpy notebook](intro_to_numpy.ipynb) complete the exercises below.

To help you out, here's a bunch of numpy methods often used in the DSI.

```python
import numpy as np

lst = [4, 1, 2, 6, 5, 3]

mtrx_A = [ [3, 2, 4],
           [1, 9, 0],
           [2, 8, 5] ]

# make a numpy array
a1 = np.array(lst) #convert a list to a numpy array
a2 = np.arange(0,12,2) #usually used for integers
a3 = np.linspace(1, 5, num=10, endpoint=True) # usually used for floats
a4 = np.array(mtrx_A)

# see the number of rows and columns in an array
shape_a1 = a1.shape
rows_a1 = a1.shape[0]
cols_a1 = a1.shape[1] # will return an error

# change the shape of an array
a1 = a1[:,np.newaxis] # makes a1 a column vector
cols_a1 = a1.shape[1] # now it does not throw an error, a1 has 1 column
a1 = a1.reshape((-1,1)) # so does this, the -1 is telling numpy to figure out the number of rows
a2.resize((3,2)) # does it inplace (note don't need a2 = a2.resize etc., asking for 2 columns

# math functions 
m1 = a1.mean() # average of entire array
m1_anotherway = np.mean(a1) # same
m4 = a4.mean() # average of entire array
m4_col_mn = a4.mean(axis = 0) # the average of each column
m4_row_mn = a4.mean(axis = 1) # the average of each row
m4_row_sum = a4.sum(axis = 1) # the sum of each row

# sorting
a1 = np.array(lst) #re-make array
a1.sort() #will sort along the longest axis, note that this is done inplace (don't need a1 = a1.sort())
a1 = a1[::-1] # reverse array order (high to low)
a4.sort(axis = 0) # columns sorted in ascending order, inplace
a4.sort(axis = 1) # rows sorted in ascending order, inplace

# working with array indices
cols = np.array(['A','B','C']) # column labels
rows = np.array(['Zeroth','First','Second','Third']) # row labels
mtrx_B = [ [3, -1, 0],
           [1, 10, 2],
           [4, -3, 9],
           [9, 11, 1] ]
indices_col_mins = np.argmin(mtrx_B, axis=0) # index of minimum value in each column
indices_row_mins = np.argmin(mtrx_B, axis=1) # index of minimum value in each row
(ind_row_min, ind_col_min) = np.where(mtrx_B == np.min(mtrx_B)) # find the row, column index of min. value
# now use indices to return the row and column labels of the minimum
print("The minimum occurs in the {0} row, {1} column.".format(rows[i_row_min][0],cols[i_col_min][0]))

```


### Question 1

Make the following matrices in numpy:

```python
arr1 = -0.2, 1.2, 3.4, 0.2

arr2 = 5  2  -3  2  
       0  3  12  3  
       2  9  10  6
```

In [1]:
import numpy as np

In [22]:
arr1 = np.array((-.2, 1.2, 3.4, .2), float)
arr1

array([-0.2,  1.2,  3.4,  0.2])

In [34]:
arr2 = np.array([5,2,-3,2,0,3,12,3,2,9,10,6]).reshape(3,4)
arr2

array([[ 5,  2, -3,  2],
       [ 0,  3, 12,  3],
       [ 2,  9, 10,  6]])

### Question 2

a) Change each array into 1 row with as many columns as necessary.  
b) Change each array into 1 column with as many rows as necessary.

In each case save the reshaped array into a different variable name.

In [10]:
#a
arr1a = arr1
arr2a = arr2.reshape((1,-1))
arr2a

array([[ 5,  2, -3,  2,  0,  3, 12,  3,  2,  9, 10,  6]])

In [11]:
#b
arr1b = arr1.reshape((-1,1))
arr1b

array([[-0.2],
       [ 1.2],
       [ 3.4],
       [ 0.2]])

In [13]:
arr2b = arr2.reshape((-1,1))
arr2b

array([[ 5],
       [ 2],
       [-3],
       [ 2],
       [ 0],
       [ 3],
       [12],
       [ 3],
       [ 2],
       [ 9],
       [10],
       [ 6]])

### Question 3

Find the array min, max, the row min, max, and the column min, max for `arr1` and `arr2`.

In [23]:
arr1.min() #array min

-0.20000000000000001

In [15]:
arr2.min() #array min

-3

In [19]:
#row mins & maxs
arr2.min(axis=1), arr2.max(axis=1)

(array([-3,  0,  2]), array([ 5, 12, 10]))

In [20]:
#column mins & maxs
arr1.min(axis=0), arr1.max(axis=0), arr2.min(axis=0), arr2.max(axis=0)

(-0.20000000000000001,
 3.3999999999999999,
 array([ 0,  2, -3,  2]),
 array([ 5,  9, 12,  6]))

### Question 4

Return `arr1` and `arr2` sorted low to high, and high to low, row-wise and column-wise.  

In [26]:
#arr1 column-wise:
arr1.sort() #sorts in-place
arr1

array([-0.2,  0.2,  1.2,  3.4])

In [28]:
#arr1 descending.  Note this takes arr1 already sorted ascending and reverses it.
arr1[::-1]

array([ 3.4,  1.2,  0.2, -0.2])

In [35]:
#arr2 row-wise ascending
np.sort(arr2, axis=1)

array([[-3,  2,  2,  5],
       [ 0,  3,  3, 12],
       [ 2,  6,  9, 10]])

In [32]:
#arr2 row-wise descending:
-np.sort(-arr2, axis=1)

array([[ 5,  2,  2, -3],
       [12,  3,  3,  0],
       [10,  9,  6,  2]])

In [38]:
#arr2 column-wise ascending:
np.sort(arr2, axis=0)

array([[ 0,  2, -3,  2],
       [ 2,  3, 10,  3],
       [ 5,  9, 12,  6]])

In [39]:
#arr2 column-wise descending:
-np.sort(-arr2, axis=0)

array([[ 5,  9, 12,  6],
       [ 2,  3, 10,  3],
       [ 0,  2, -3,  2]])

### Question 5

Find the row and column of the maximum value `arr1` and `arr2`.  Print them out nicely.

In [44]:
np.argmax(arr1)

3

In [55]:
arr2

array([[ 5,  2, -3,  2],
       [ 0,  3, 12,  3],
       [ 2,  9, 10,  6]])

In [53]:
i_rowmax, i_colmax = np.where(arr2 == np.max(arr2))
print('The maximum of arr2 occurs in row {}, column {}.'.format(i_rowmax[0], i_colmax[0]))

The maximum of r2 occurs in row 1, column 2.
